import "../globals.css";
import "../../scss/style.scss";
import "../../css/bs-compiled.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "./local.scss";

export const metadata = {
  title: "CarCien",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <Header />
        <main>{children}</main>
        <Footer className="mt-auto" />
      </body>
    </html>
  );
}
